apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migration-0-name" . }}
spec:
  template:
    spec:
      containers:
      - name: pg
        image: postgres:16.3-bookworm
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: postgresqlPassword
        command: ["/bin/sh"]
        args:
        - -c
        - >-
          psql -c "create database otusms" --host={{ include "db-service-name" . }} --port=5432 --username=postgres &&
          psql -c "create table if not exists public.user(id serial primary key, username text, firstname text, lastname text, email text, phone text);" --host={{ include "db-service-name" . }} --port=5432 --username=postgres --dbname=otusms
      restartPolicy: Never
  backoffLimit: 5
