apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-service-name" . }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: {{ include "db-service-node-port" . }}
