{
 "title": "Otus - Microservices",
 "time": { "from": "2024-06-14T19:47:48.958Z", "to": "2024-06-14T20:20:12.850Z" },
 "panels": [
  {
   "title": "RPS (from application)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))-sum(rate(http_requests_received_total{code=\"500\"}[1m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=\"500\"}[1m]))",
     "legendFormat": "Only 500"
    }
   ]
  },
  {
   "title": "Latency (response time, from application)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 1"
    }
   ]
  },
  {
   "title": "RPS (from ingress-nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m]))",
     "legendFormat": "Only 500"
    }
   ]
  },
  {
   "title": "Latency (response time, from nginx-ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Quantile 1"
    }
   ]
  }
 ]
}